### ISSUE TITLE
Unresolved class `Bencode` in Android-JVM MPP

### ISSUE THREAD

**Issue by Him188** [iseki0/kotlinx-serialization-bencoding#2]
![image](https://github.com/iseki0/kotlinx-serialization-bencoding/assets/12100985/5119615c-804d-425f-933f-5333c4070bd6)

Targets:

```
kotlin {
    androidTarget()
    jvm("desktop")
}
```

![image](https://github.com/iseki0/kotlinx-serialization-bencoding/assets/12100985/08f73ddd-74a3-48e3-b7b0-296f32e3feac)

**Comment by iseki0** [comment]
😥Sorry. The project is currently under development, do you need the decoder only? I will complete it soon.
Regarding the unresolved reference, there's an incompatible API change. The old version used `InputStream.decodeInBencoding<T>`, which doesn't follow the `BinaryFormat` type in the `kotlinx-serialization-core`. In the next version I will update it to match the README.  @Him188

**Comment by iseki0** [comment]
The encoder part is currently under development in another repo, after I complete the unit test it will be merged. Before that if you need the fully tested decoder API, let me know, I will make a release. (The decoder development was completed but not release yet.) @Him188

**Comment by Him188** [comment]
No worries at all @iseki0, thanks for your work. 

I turned to another Bencode decoder written in Java. Since both desktop and Android targets support Java-interop, this is not a problem. 

Here is the relevant code:
https://github.com/open-ani/ani/blob/043a346f06fae777cf846556ff2c15f5157063c2/torrent/impl/qbittorrent/src/QBittorrentTorrentDownloader.kt#L104

I'm happy to move to your library when it gets stable in the future :)

**Comment by Him188** [comment]
I also authorize Kotlin multiplatform libraries like [mirai](https://github.com/mamoe/mirai), so I'm a _bit_ familiar with the multiplatform build logic.

I looked through your buildscript. It looks like you are requiring JVM target 17, which sounds too high for a library.
Officially the minimum JVM target is 8 and most of the libraries support 8 so that they can work on all projects.
Do you need any specific features from JDK 17? If not, I think we should set it to 8. 
Also we can remove `withJava()` here?

```kotlin
    jvmToolchain(22)
    jvm {
        @OptIn(ExperimentalKotlinGradlePluginApi::class) compilerOptions {
            jvmTarget = JvmTarget.JVM_17
            freeCompilerArgs.add("-Xjvm-default=all")
        }
        withJava()
    }
```

These changes might help solve the original dependency resolution problem. 

However, I also suspect It might be a Kotlin bug:
https://youtrack.jetbrains.com/issue/KT-65362/Cannot-resolve-declarations-from-a-dependency-when-there-are-multiple-JVM-only-project-dependencies-in-a-JVM-Android-MPP

**Comment by iseki0** [comment]
@Him188 Thank you for your advice. 
I set the toolchain to Java 22 just because I want to test it in the Graalvm Native Image environment in the old days. Now I will consider to reduce the toolchain version. (I don't think it's required now.)
I configure the target to 17 version just because I want to give supports to JPMS(Jigsaw), even I don't like it. 
Since the most Android application require the target 8, your advice is very valuable.
I will reduce the target version to 8. And the `module-info.class` could be added by [multi-release jar](https://blog.gradle.org/mrjars#how-to-create-a-multi-release-jar-with-gradle), just like the many libraries chosen.
